# =============================================================================
# SEED DATA — Canonical source for all test records
# Imported by seed_db.py (and indirectly by reset_db.py)
# =============================================================================

# ── SUPER ADMIN ──────────────────────────────────────────────────────────────
ADMIN = {
    "email": "admin@jobportal.com",
    "password": "Admin@123",
    "full_name": "Platform Admin",
}

# ── AGENTS (2) ───────────────────────────────────────────────────────────────
AGENTS = [
    {
        "email": "rajesh.agent@jobportal.com",
        "password": "Agent@123",
        "full_name": "Rajesh Malhotra",
        "referral_code": "AGENT-IND-00001",
        "phone": "+919876543211",
        "dob": "1988-05-15",
        "profile_pic": "",
        "doc_type": "PAN",
        "doc_number": "ABCDE1234F",
        "payout_type": "UPI",
        "upi_id": "rajesh.malhotra@ybl",
    },
    {
        "email": "priya.agent@jobportal.com",
        "password": "Agent@123",
        "full_name": "Priya Sharma",
        "referral_code": "AGENT-IND-00002",
        "phone": "+919876543212",
        "dob": "1992-11-20",
        "profile_pic": "",
        "doc_type": "Aadhar",
        "doc_number": "123456789012",
        "payout_type": "Bank",
        "bank_name": "HDFC Bank",
        "account_holder": "Priya Sharma",
        "account_number": "50100234567890",
        "ifsc_code": "HDFC0000123",
        "micr_code": "560240012",
    },
]

# ── EMPLOYERS (12 total — 5 under Agent-1, 7 under Agent-2) ─────────────────
EMPLOYERS = [
    # ─── Referred by AGENT-IND-00001 (indexes 0–4) ───────────────────────────
    {
        "email": "amit@apexinnovations.com",
        "password": "Employer@123",
        "full_name": "Amit Goel",
        "company_name": "Apex Innovations",
        "industry": "Information Technology",
        "city": "Bangalore",
        "whatsapp_number": "+919988776655",
        "address": "42, Tech Park Ring Rd, Bangalore",
        "is_verified": True,
        "agent_index": 0,          # → AGENT-IND-00001
    },
    {
        "email": "rohan@quantumlabs.ai",
        "password": "Employer@123",
        "full_name": "Rohan Gupta",
        "company_name": "Quantum Labs",
        "industry": "Artificial Intelligence",
        "city": "Hyderabad",
        "whatsapp_number": "+919876123456",
        "address": "Gachibowli AI Corridor, Hyderabad",
        "is_verified": True,
        "agent_index": 0,
    },
    {
        "email": "kavita@fintechsolutions.in",
        "password": "Employer@123",
        "full_name": "Kavita Reddy",
        "company_name": "Fintech Solutions Ltd",
        "industry": "Banking & Finance",
        "city": "Mumbai",
        "whatsapp_number": "+918877665544",
        "address": "Bandra Kurla Complex, Mumbai",
        "is_verified": True,
        "agent_index": 0,
    },
    {
        "email": "siddharth@cloudsphere.io",
        "password": "Employer@123",
        "full_name": "Siddharth Sen",
        "company_name": "CloudSphere Technologies",
        "industry": "Cloud Infrastructure",
        "city": "Pune",
        "whatsapp_number": "+917766554433",
        "address": "Hinjewadi Phase 2, Pune",
        "is_verified": True,
        "agent_index": 0,
    },
    {
        "email": "ananya@healthify.in",
        "password": "Employer@123",
        "full_name": "Ananya Roy",
        "company_name": "Healthify Systems",
        "industry": "Healthcare Tech",
        "city": "Chennai",
        "whatsapp_number": "+916655443322",
        "address": "OMR Tech Expressway, Chennai",
        "is_verified": True,
        "agent_index": 0,
    },
    # ─── Referred by AGENT-IND-00002 (indexes 5–11) ─────────────────────────
    {
        "email": "vikram@logiroute.com",
        "password": "Employer@123",
        "full_name": "Vikram Rathore",
        "company_name": "LogiRoute Logistics",
        "industry": "Supply Chain & Logistics",
        "city": "Gurgaon",
        "whatsapp_number": "+919555123456",
        "address": "Sector 48 Sohna Road, Gurgaon",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "meera@edulearn.co.in",
        "password": "Employer@123",
        "full_name": "Meera Joshi",
        "company_name": "EduLearn Academy",
        "industry": "E-Learning",
        "city": "Delhi",
        "whatsapp_number": "+919444123456",
        "address": "Connaught Place, New Delhi",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "deepak@solaris-energy.in",
        "password": "Employer@123",
        "full_name": "Deepak Verma",
        "company_name": "Solaris Energy",
        "industry": "Renewable Resources",
        "city": "Noida",
        "whatsapp_number": "+919333123456",
        "address": "Sector 62, Noida",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "ayesha@designcraft.studio",
        "password": "Employer@123",
        "full_name": "Ayesha Khan",
        "company_name": "DesignCraft Studio",
        "industry": "Creative & Design",
        "city": "Mumbai",
        "whatsapp_number": "+919222123456",
        "address": "Andheri West, Mumbai",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "arjun@cybershield.io",
        "password": "Employer@123",
        "full_name": "Arjun Saxena",
        "company_name": "CyberShield Security",
        "industry": "Cybersecurity",
        "city": "Bangalore",
        "whatsapp_number": "+919111123456",
        "address": "Whitefield Main Road, Bangalore",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "sneha@aerotech.co.in",
        "password": "Employer@123",
        "full_name": "Sneha Nair",
        "company_name": "AeroTech Aerospace",
        "industry": "Aerospace Engineering",
        "city": "Trivandrum",
        "whatsapp_number": "+919000123456",
        "address": "Technopark Campus, Trivandrum",
        "is_verified": True,
        "agent_index": 1,
    },
    {
        "email": "gaurav@biohealth.in",
        "password": "Employer@123",
        "full_name": "Gaurav Malhotra",
        "company_name": "BioHealth Pharma",
        "industry": "Pharmaceuticals",
        "city": "Ahmedabad",
        "whatsapp_number": "+918999123456",
        "address": "Sarkhej-Gandhinagar Highway, Ahmedabad",
        "is_verified": True,
        "agent_index": 1,
    },
]

# ── JOB POSTINGS (5 per employer, keyed by employer index 0–11) ─────────────
# Each list of 5 has varied titles, categories, salary bands, experience, and flags.
JOB_POSTINGS = {
    # ──── Employer 0: Apex Innovations (IT) ──────────────────────────────────
    0: [
        {
            "title": "Senior React Developer",
            "category": "Information Technology (IT)",
            "salary": "₹12,00,000 - ₹18,00,000 PA",
            "type": "Full-time",
            "description": "Build scalable single-page applications using React 18+, TypeScript, and modern state management libraries. Collaborate with product designers to ship pixel-perfect UIs.",
            "requirements": "3+ years with React, proficiency in TypeScript, familiarity with CI/CD pipelines.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "DevOps Cloud Engineer",
            "category": "Information Technology (IT)",
            "salary": "₹15,00,000 - ₹22,00,000 PA",
            "type": "Full-time",
            "description": "Architect and maintain multi-region AWS infrastructure. Automate deployments with Terraform, manage Kubernetes clusters, and implement cost-optimization strategies.",
            "requirements": "4+ years in DevOps, hands-on with AWS/GCP, Kubernetes CKA preferred.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Frontend Engineering Intern",
            "category": "Freelance & Gig Economy",
            "salary": "₹25,000 / month",
            "type": "Internship",
            "description": "Assist the frontend squad in building reusable component libraries and writing unit tests. Ideal for final-year CS students eager to learn React and Next.js.",
            "requirements": "Pursuing B.Tech/MCA, basic knowledge of HTML, CSS, JavaScript.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Staff Full-Stack Engineer",
            "category": "Information Technology (IT)",
            "salary": "₹24,00,000 - ₹35,00,000 PA",
            "type": "Full-time",
            "description": "Own end-to-end feature delivery across the Node.js API layer and React front end. Mentor mid-level engineers, participate in architecture reviews, and drive technical standards.",
            "requirements": "8+ years full-stack, strong system design skills, experience leading squads.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "UI/UX Designer",
            "category": "Design & Creative Arts",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Conduct user research, create wireframes, high-fidelity prototypes, and design systems in Figma. Work closely with engineers to ensure design-to-code fidelity.",
            "requirements": "2+ years in product design, strong Figma portfolio, understanding of accessibility guidelines.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 1: Quantum Labs (AI) ──────────────────────────────────────
    1: [
        {
            "title": "Machine Learning Engineer",
            "category": "Information Technology (IT)",
            "salary": "₹18,00,000 - ₹28,00,000 PA",
            "type": "Full-time",
            "description": "Design, train, and deploy production-grade ML models. Build feature engineering pipelines and integrate models into low-latency serving infrastructure.",
            "requirements": "3+ years ML, proficiency in Python/PyTorch, MLOps experience preferred.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Data Scientist – Recommendation Systems",
            "category": "Information Technology (IT)",
            "salary": "₹14,00,000 - ₹22,00,000 PA",
            "type": "Full-time",
            "description": "Develop collaborative filtering and content-based recommendation engines. Analyze A/B test results and drive measurable improvements in user engagement metrics.",
            "requirements": "2+ years data science, strong SQL, experience with Spark or Flink.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "NLP Research Scientist",
            "category": "Information Technology (IT)",
            "salary": "₹20,00,000 - ₹30,00,000 PA",
            "type": "Full-time",
            "description": "Push the boundaries of transformer-based language models. Publish research, prototype novel architectures, and collaborate with the product team on LLM-powered features.",
            "requirements": "PhD or equivalent experience in NLP, publications in ACL/EMNLP/NeurIPS.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "AI Product Manager",
            "category": "Information Technology (IT)",
            "salary": "₹22,00,000 - ₹32,00,000 PA",
            "type": "Full-time",
            "description": "Define the product roadmap for AI-driven features. Translate business goals into technical requirements, coordinate cross-functional teams, and own KPI dashboards.",
            "requirements": "6+ years PM experience, technical background, familiarity with ML lifecycle.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Python Backend Intern",
            "category": "Freelance & Gig Economy",
            "salary": "₹30,000 / month",
            "type": "Internship",
            "description": "Support the backend team in building FastAPI services, writing integration tests, and automating data ingestion workflows. Great exposure to production-grade Python.",
            "requirements": "Final-year student, comfortable with Python, basic understanding of REST APIs.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 2: Fintech Solutions Ltd (Banking & Finance) ──────────────
    2: [
        {
            "title": "Java Backend Tech Lead",
            "category": "Information Technology (IT)",
            "salary": "₹25,00,000 - ₹38,00,000 PA",
            "type": "Full-time",
            "description": "Lead the core banking microservices team. Design event-driven architectures on Kafka, ensure PCI-DSS compliance, and oversee code quality across 8 services.",
            "requirements": "7+ years Java, Spring Boot expertise, experience in regulated fintech environments.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Quantitative Analyst",
            "category": "Finance & Accounting",
            "salary": "₹20,00,000 - ₹35,00,000 PA",
            "type": "Full-time",
            "description": "Build pricing models for derivatives, perform Monte Carlo simulations, and develop risk analytics dashboards for the trading desk.",
            "requirements": "M.Sc./PhD in Mathematics or Finance, strong Python/R skills, knowledge of Black-Scholes.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Financial Risk Manager",
            "category": "Finance & Accounting",
            "salary": "₹15,00,000 - ₹25,00,000 PA",
            "type": "Full-time",
            "description": "Assess credit, market, and operational risks. Prepare regulatory filings for RBI compliance and implement stress-testing frameworks.",
            "requirements": "FRM/CFA certification preferred, 4+ years in risk management.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Database Administrator",
            "category": "Information Technology (IT)",
            "salary": "₹10,00,000 - ₹16,00,000 PA",
            "type": "Full-time",
            "description": "Manage high-availability PostgreSQL and Oracle clusters. Optimize query performance, implement backup/recovery strategies, and enforce data-security policies.",
            "requirements": "3+ years DBA, experience with replication setups and performance tuning.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "QA Security Engineer",
            "category": "Information Technology (IT)",
            "salary": "₹12,00,000 - ₹20,00,000 PA",
            "type": "Full-time",
            "description": "Perform penetration testing and security audits on payment gateways. Write automated security regression suites and collaborate with SOC teams on incident response.",
            "requirements": "3+ years security testing, OWASP expertise, CEH/OSCP certification a plus.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 3: CloudSphere Technologies (Cloud) ───────────────────────
    3: [
        {
            "title": "Cloud Solutions Architect",
            "category": "Information Technology (IT)",
            "salary": "₹30,00,000 - ₹45,00,000 PA",
            "type": "Full-time",
            "description": "Design multi-cloud reference architectures for enterprise clients. Lead proof-of-concept engagements and publish technical whitepapers for the sales engineering team.",
            "requirements": "10+ years infrastructure, AWS SA Professional + Azure Architect Expert.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "AWS Support Engineer",
            "category": "Information Technology (IT)",
            "salary": "₹8,00,000 - ₹13,00,000 PA",
            "type": "Full-time",
            "description": "Provide L2/L3 support for customers running workloads on AWS. Troubleshoot EC2, RDS, and Lambda issues, and create runbooks for common failure modes.",
            "requirements": "2+ years AWS, AWS Developer/SysOps Associate certification.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Kubernetes Platform Specialist",
            "category": "Information Technology (IT)",
            "salary": "₹16,00,000 - ₹24,00,000 PA",
            "type": "Full-time",
            "description": "Build and operate production Kubernetes clusters using EKS/AKS. Implement service mesh (Istio), GitOps workflows (ArgoCD), and zero-downtime deployment pipelines.",
            "requirements": "4+ years K8s, CKA/CKAD certified, experience with Helm and Kustomize.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Network Security Administrator",
            "category": "Information Technology (IT)",
            "salary": "₹11,00,000 - ₹17,00,000 PA",
            "type": "Full-time",
            "description": "Manage firewalls, VPNs, and IDS/IPS systems across cloud and on-prem networks. Conduct vulnerability assessments and enforce zero-trust network policies.",
            "requirements": "3+ years networking, CCNA/CCNP, familiarity with Palo Alto or Fortinet.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Technical Writer – Cloud Documentation",
            "category": "Design & Creative Arts",
            "salary": "₹6,00,000 - ₹9,00,000 PA",
            "type": "Full-time",
            "description": "Author API reference guides, migration playbooks, and developer tutorials for CloudSphere's platform. Maintain a docs-as-code pipeline using Markdown and Docusaurus.",
            "requirements": "1+ year technical writing, ability to read code in Python/Go, excellent English.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 4: Healthify Systems (Healthcare Tech) ────────────────────
    4: [
        {
            "title": "Bioinformatics Developer",
            "category": "Healthcare",
            "salary": "₹12,00,000 - ₹20,00,000 PA",
            "type": "Full-time",
            "description": "Build genomic data pipelines using Python and R. Integrate with FHIR-based EHR systems and visualize patient outcome trends for clinical research teams.",
            "requirements": "2+ years bioinformatics, experience with Nextflow/Snakemake, biology domain knowledge.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Android Healthcare App Developer",
            "category": "Information Technology (IT)",
            "salary": "₹10,00,000 - ₹16,00,000 PA",
            "type": "Full-time",
            "description": "Develop and maintain a patient-facing health tracker on Android (Kotlin + Jetpack Compose). Integrate wearable APIs and ensure HIPAA-compliant data handling.",
            "requirements": "3+ years Android/Kotlin, experience with Health Connect API preferred.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Healthcare Data Analyst",
            "category": "Information Technology (IT)",
            "salary": "₹7,00,000 - ₹11,00,000 PA",
            "type": "Full-time",
            "description": "Analyze patient engagement data, build dashboards in Metabase/Looker, and generate weekly insights reports for the product and clinical affairs teams.",
            "requirements": "1+ year analytics, SQL proficiency, familiarity with healthcare KPIs.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Compliance & Quality Officer",
            "category": "Information Technology (IT)",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Ensure adherence to NABH and ISO 13485 standards. Conduct internal audits, manage CAPA processes, and liaise with regulatory bodies during inspections.",
            "requirements": "3+ years quality/compliance in healthcare, familiarity with FDA 21 CFR Part 11.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Systems Administrator",
            "category": "Information Technology (IT)",
            "salary": "₹9,00,000 - ₹14,00,000 PA",
            "type": "Full-time",
            "description": "Manage on-prem and hybrid-cloud server infrastructure. Administer Active Directory, implement backup strategies, and ensure 99.9% uptime SLAs for hospital systems.",
            "requirements": "2+ years sysadmin, Linux + Windows Server, experience with VMware/Hyper-V.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 5: LogiRoute Logistics (Supply Chain) ─────────────────────
    5: [
        {
            "title": "Supply Chain Coordinator",
            "category": "Transportation & Logistics",
            "salary": "₹6,00,000 - ₹9,00,000 PA",
            "type": "Full-time",
            "description": "Coordinate shipments across 12 distribution centres. Negotiate with transporters, track consignments in real-time, and resolve delivery exceptions promptly.",
            "requirements": "2+ years logistics, proficiency in SAP MM, strong communication skills.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Logistics Route Optimisation Planner",
            "category": "Transportation & Logistics",
            "salary": "₹5,00,000 - ₹8,00,000 PA",
            "type": "Full-time",
            "description": "Use OR-based routing algorithms and fleet GPS data to optimise last-mile delivery routes, reducing fuel costs and improving on-time delivery percentages.",
            "requirements": "1+ year in route planning, analytical mindset, familiarity with GIS tools.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Warehouse Operations Lead",
            "category": "Transportation & Logistics",
            "salary": "₹7,00,000 - ₹11,00,000 PA",
            "type": "Full-time",
            "description": "Supervise a 40-member warehouse team. Implement lean 5S methodologies, manage inventory accuracy above 99.5%, and oversee WMS configuration and training.",
            "requirements": "3+ years warehouse management, experience with WMS (Manhattan/Blue Yonder).",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Operations Systems Analyst",
            "category": "Information Technology (IT)",
            "salary": "₹11,00,000 - ₹16,00,000 PA",
            "type": "Full-time",
            "description": "Develop internal tools and dashboards that connect TMS, WMS, and ERP systems. Automate reporting workflows and create data pipelines for operational analytics.",
            "requirements": "3+ years systems analysis, Python/SQL, experience integrating enterprise software.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Procurement Manager",
            "category": "Transportation & Logistics",
            "salary": "₹12,00,000 - ₹18,00,000 PA",
            "type": "Full-time",
            "description": "Source and negotiate contracts for packaging materials and fleet spare-parts. Manage vendor scorecards, drive cost-reduction initiatives, and ensure compliance with procurement policies.",
            "requirements": "5+ years procurement, strong negotiation skills, CIPS certification a plus.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 6: EduLearn Academy (E-Learning) ──────────────────────────
    6: [
        {
            "title": "Senior Curriculum Designer",
            "category": "Education",
            "salary": "₹9,00,000 - ₹14,00,000 PA",
            "type": "Full-time",
            "description": "Design outcome-based curricula for K-12 and competitive exam prep courses. Align content with NEP 2020 guidelines and incorporate gamification elements.",
            "requirements": "4+ years instructional design, experience with SCORM/xAPI, education domain expertise.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Instructional Video Editor",
            "category": "Design & Creative Arts",
            "salary": "₹6,00,000 - ₹9,00,000 PA",
            "type": "Full-time",
            "description": "Edit lecture recordings, add motion graphics overlays, and produce engaging 10-15 minute video lessons. Manage the post-production pipeline from raw footage to final QC.",
            "requirements": "2+ years video editing, Premiere Pro/DaVinci Resolve, basic After Effects.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "LMS Platform Developer",
            "category": "Information Technology (IT)",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Maintain and extend our custom Learning Management System built on Django. Implement progress tracking, assessment engines, and learner analytics modules.",
            "requirements": "2+ years Django/Python, REST API design, familiarity with Celery and Redis.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Online Tutor Coordinator",
            "category": "Education",
            "salary": "₹5,00,000 - ₹8,00,000 PA",
            "type": "Full-time",
            "description": "Manage a roster of 200+ freelance tutors. Schedule live sessions, monitor quality scores, handle escalations, and onboard new tutors onto the platform.",
            "requirements": "1+ year coordination role, excellent organisational skills, comfort with spreadsheets.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Academic Content Writer",
            "category": "Design & Creative Arts",
            "salary": "₹4,50,000 - ₹7,00,000 PA",
            "type": "Full-time",
            "description": "Write clear, student-friendly explanations for Mathematics and Science topics (Class 6-12). Create practice question banks with detailed step-by-step solutions.",
            "requirements": "1+ year content writing, strong grasp of CBSE/ICSE syllabus, research aptitude.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 7: Solaris Energy (Renewable Resources) ───────────────────
    7: [
        {
            "title": "Renewable Energy Systems Engineer",
            "category": "Energy & Utilities",
            "salary": "₹14,00,000 - ₹22,00,000 PA",
            "type": "Full-time",
            "description": "Design and commission grid-tied and off-grid solar installations up to 10 MW. Perform PVsyst simulations, manage BoS procurement, and oversee site engineers.",
            "requirements": "4+ years solar EPC, P.E. license preferred, experience with SCADA systems.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Solar Grid Consultant",
            "category": "Energy & Utilities",
            "salary": "₹10,00,000 - ₹16,00,000 PA",
            "type": "Full-time",
            "description": "Advise utility companies on grid-integration challenges of intermittent solar generation. Conduct power-flow studies, harmonic analyses, and interconnection feasibility reports.",
            "requirements": "3+ years power systems, knowledge of IEEE 1547, PSS/E or ETAP proficiency.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Environmental Impact Analyst",
            "category": "Energy & Utilities",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Prepare EIA reports for new solar and wind farm projects. Interface with MoEFCC for clearances, conduct baseline surveys, and develop mitigation plans.",
            "requirements": "2+ years environmental consulting, familiarity with EIA notification 2006.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Power Infrastructure Project Lead",
            "category": "Energy & Utilities",
            "salary": "₹18,00,000 - ₹28,00,000 PA",
            "type": "Full-time",
            "description": "Manage multi-crore solar park projects from land acquisition through commissioning. Coordinate civil, electrical, and transmission work-streams and report progress to CXOs.",
            "requirements": "6+ years project management, PMP certified, EPC background mandatory.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Field Research Assistant – Solar",
            "category": "Energy & Utilities",
            "salary": "₹5,00,000 - ₹8,00,000 PA",
            "type": "Full-time",
            "description": "Collect on-site irradiance, temperature, and module-degradation data. Maintain weather stations, calibrate sensors, and upload data to the central SCADA database.",
            "requirements": "B.Sc./B.Tech in Physics or EE, willingness to travel to rural sites 50% of the time.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 8: DesignCraft Studio (Creative & Design) ─────────────────
    8: [
        {
            "title": "Product Graphic Designer",
            "category": "Design & Creative Arts",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Create packaging artwork, marketing collateral, and social-media creatives for FMCG and D2C brands. Manage multiple projects simultaneously with tight turnaround times.",
            "requirements": "2+ years graphic design, expert in Illustrator + Photoshop, print production knowledge.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Senior Motion Graphics Artist",
            "category": "Design & Creative Arts",
            "salary": "₹12,00,000 - ₹18,00,000 PA",
            "type": "Full-time",
            "description": "Produce animated explainer videos, logo reveals, and interactive AR filters. Build and maintain a shared After Effects template library for the studio.",
            "requirements": "4+ years motion design, After Effects + Cinema 4D, understanding of 12 principles of animation.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "UI/UX Design Lead",
            "category": "Design & Creative Arts",
            "salary": "₹18,00,000 - ₹28,00,000 PA",
            "type": "Full-time",
            "description": "Lead the design practice for client engagements across mobile and web. Establish design systems, mentor junior designers, and present design rationale to C-suite stakeholders.",
            "requirements": "6+ years product design, Figma design-system experience, agency background preferred.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Creative Art Director",
            "category": "Design & Creative Arts",
            "salary": "₹22,00,000 - ₹35,00,000 PA",
            "type": "Full-time",
            "description": "Set the creative vision for brand campaigns spanning digital, OOH, and experiential. Direct photo shoots, approve final artworks, and ensure brand consistency across touch-points.",
            "requirements": "8+ years creative leadership, award-winning portfolio, ability to manage a team of 6+.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "3D Modeler (Blender/Maya)",
            "category": "Design & Creative Arts",
            "salary": "₹7,00,000 - ₹11,00,000 PA",
            "type": "Full-time",
            "description": "Model product mockups, architectural visualisations, and character assets in Blender. Optimise geometry for real-time WebGL rendering on e-commerce platforms.",
            "requirements": "1+ year 3D modelling, strong topology awareness, texture painting skills.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 9: CyberShield Security (Cybersecurity) ──────────────────
    9: [
        {
            "title": "Security Operations Centre Analyst",
            "category": "Information Technology (IT)",
            "salary": "₹11,00,000 - ₹16,00,000 PA",
            "type": "Full-time",
            "description": "Monitor SIEM alerts 24×7, perform triage on security incidents, and escalate confirmed threats to the IR team. Write daily shift reports and maintain playbook documentation.",
            "requirements": "3+ years SOC, experience with Splunk/QRadar, CompTIA Security+ certified.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Lead Penetration Tester",
            "category": "Information Technology (IT)",
            "salary": "₹16,00,000 - ₹25,00,000 PA",
            "type": "Full-time",
            "description": "Conduct red-team engagements for enterprise clients: network, web-app, and wireless pen testing. Deliver executive-ready reports with CVSS-scored findings and remediation guidance.",
            "requirements": "5+ years offensive security, OSCP/OSCE certified, scripting in Python/Bash.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "IAM Security Specialist",
            "category": "Information Technology (IT)",
            "salary": "₹12,00,000 - ₹19,00,000 PA",
            "type": "Full-time",
            "description": "Implement and manage identity and access management solutions (Okta, Azure AD). Design RBAC/ABAC policies, automate user lifecycle events, and enforce MFA across the organisation.",
            "requirements": "3+ years IAM, experience with SAML/OIDC/OAuth 2.0, scripting for automation.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "GRC Coordinator",
            "category": "Information Technology (IT)",
            "salary": "₹14,00,000 - ₹20,00,000 PA",
            "type": "Full-time",
            "description": "Drive ISO 27001 and SOC 2 Type II compliance programs. Maintain the risk register, coordinate internal audits, and prepare evidence packages for external assessors.",
            "requirements": "4+ years GRC, CISA/CRISC certification, experience with GRC tools like Archer or ServiceNow.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Network Intrusion Detection Specialist",
            "category": "Information Technology (IT)",
            "salary": "₹10,00,000 - ₹15,00,000 PA",
            "type": "Full-time",
            "description": "Deploy and tune Suricata/Zeek sensors across client networks. Analyse PCAP captures, write custom detection rules, and integrate findings into the threat-intel platform.",
            "requirements": "2+ years network security, deep TCP/IP knowledge, Snort/Suricata rule writing.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 10: AeroTech Aerospace (Aerospace Engineering) ────────────
    10: [
        {
            "title": "Embedded Avionics Developer",
            "category": "Engineering",
            "salary": "₹15,00,000 - ₹24,00,000 PA",
            "type": "Full-time",
            "description": "Write DO-178C compliant embedded C/C++ firmware for flight management systems. Perform MISRA checks, HIL testing, and integrate with ARINC 429 / MIL-STD-1553 buses.",
            "requirements": "4+ years embedded systems, DO-178C DAL-A experience, RTOS (VxWorks/INTEGRITY).",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Aerodynamics Consultant",
            "category": "Engineering",
            "salary": "₹18,00,000 - ₹30,00,000 PA",
            "type": "Full-time",
            "description": "Conduct CFD analyses for wing and fuselage geometries. Optimise drag coefficients through parametric studies and validate results against wind-tunnel data.",
            "requirements": "5+ years aero, proficiency in ANSYS Fluent or OpenFOAM, M.Tech in Aerospace.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Flight Control Systems Engineer",
            "category": "Engineering",
            "salary": "₹14,00,000 - ₹22,00,000 PA",
            "type": "Full-time",
            "description": "Design and verify fly-by-wire control laws using MATLAB/Simulink. Perform stability and handling-qualities analyses per MIL-HDBK-1797 and support flight-test campaigns.",
            "requirements": "3+ years controls, model-based design experience, familiarity with ARP 4754A.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "RF Communication Engineer",
            "category": "Engineering",
            "salary": "₹11,00,000 - ₹17,00,000 PA",
            "type": "Full-time",
            "description": "Design satellite communication sub-systems (S-band/X-band). Perform link-budget analyses, prototype antenna feeds, and support environmental qualification testing.",
            "requirements": "2+ years RF design, familiarity with spectrum analysers and VNA, HFSS/CST experience.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "CAD Modelling Specialist",
            "category": "Engineering",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Create detailed 3D models and assemblies of structural airframe components in CATIA V5/NX. Generate 2D GD&T drawings and maintain the engineering BOM in PLM systems.",
            "requirements": "2+ years CAD, CATIA V5 expertise, understanding of aerospace materials (composites, Ti alloys).",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
    # ──── Employer 11: BioHealth Pharma (Pharmaceuticals) ────────────────────
    11: [
        {
            "title": "Lead Formulation Scientist",
            "category": "Biotechnology & Pharmaceuticals",
            "salary": "₹12,00,000 - ₹18,00,000 PA",
            "type": "Full-time",
            "description": "Develop oral solid-dosage formulations from pre-formulation through scale-up. Design DOE studies for process optimisation and author CMC sections of ANDA/NDA dossiers.",
            "requirements": "4+ years formulation R&D, M.Pharm, experience with granulation and coating processes.",
            "is_urgent": True,
            "is_featured": True,
        },
        {
            "title": "Clinical Trials Data Analyst",
            "category": "Biotechnology & Pharmaceuticals",
            "salary": "₹9,00,000 - ₹14,00,000 PA",
            "type": "Full-time",
            "description": "Perform statistical analyses for Phase II/III clinical trials using SAS and R. Generate TLFs (Tables, Listings, Figures) and support data-management activities.",
            "requirements": "2+ years biostatistics, SAS Base/Advanced certified, ICH-GCP knowledge.",
            "is_urgent": False,
            "is_featured": True,
        },
        {
            "title": "Pharma Regulatory Affairs Specialist",
            "category": "Biotechnology & Pharmaceuticals",
            "salary": "₹10,00,000 - ₹15,00,000 PA",
            "type": "Full-time",
            "description": "Prepare and file CDSCO and FDA regulatory submissions. Track post-approval commitments, manage variation applications, and liaise with regulatory agencies during queries.",
            "requirements": "3+ years regulatory affairs, knowledge of CTD/eCTD format, pharma background.",
            "is_urgent": True,
            "is_featured": False,
        },
        {
            "title": "Medical Safety & Pharmacovigilance Officer",
            "category": "Biotechnology & Pharmaceuticals",
            "salary": "₹8,00,000 - ₹12,00,000 PA",
            "type": "Full-time",
            "description": "Process ICSRs within regulatory timelines, author PSURs, and conduct signal-detection analyses. Maintain the safety database (Argus/ArisGlobal) and train CRO partners on AE reporting.",
            "requirements": "2+ years PV, MBBS/BDS/M.Pharm, familiarity with MedDRA coding.",
            "is_urgent": False,
            "is_featured": False,
        },
        {
            "title": "Quality Control Lab Technician",
            "category": "Biotechnology & Pharmaceuticals",
            "salary": "₹5,00,000 - ₹8,00,000 PA",
            "type": "Full-time",
            "description": "Perform HPLC, dissolution, and Karl-Fischer analyses on finished dosage forms. Calibrate lab instruments, maintain logbooks per GLP standards, and flag OOS results promptly.",
            "requirements": "B.Sc./M.Sc. Chemistry, 1+ year QC lab, basic HPLC troubleshooting ability.",
            "is_urgent": False,
            "is_featured": False,
        },
    ],
}
