import React, { useState, useEffect } from 'react';

const sections = [
  { id: 'introduction', label: 'Introduction' },
  { id: 'information-we-collect', label: 'Information We Collect' },
  { id: 'how-we-use', label: 'How We Use Your Data' },
  { id: 'legal-basis', label: 'Legal Basis for Processing' },
  { id: 'sharing', label: 'Sharing & Disclosure' },
  { id: 'data-security', label: 'Data Security' },
  { id: 'your-rights', label: 'Your Rights' },
  { id: 'retention', label: 'Data Retention' },
  { id: 'cookies', label: 'Cookies' },
  { id: 'changes', label: 'Changes to This Policy' },
  { id: 'grievance', label: 'Grievance Officer' },
];

const PrivacyPolicy = () => {
  const [active, setActive] = useState('introduction');

  useEffect(() => {
    const onScroll = () => {
      let current = 'introduction';
      for (const s of sections) {
        const el = document.getElementById(s.id);
        if (el && el.getBoundingClientRect().top <= 100) current = s.id;
      }
      setActive(current);
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const scrollTo = (id) => {
    const el = document.getElementById(id);
    if (el) {
      const y = el.getBoundingClientRect().top + window.pageYOffset - 80;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  return (
    <div className="bg-white min-h-screen pt-28">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <div className="flex gap-16 items-start">

          {/* Sticky TOC */}
          <aside className="hidden lg:block w-56 shrink-0 sticky top-24">
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-widest mb-4">On this page</p>
            <nav className="space-y-1">
              {sections.map(s => (
                <button
                  key={s.id}
                  onClick={() => scrollTo(s.id)}
                  className={`block w-full text-left text-xs py-1.5 px-0 border-0 bg-transparent cursor-pointer transition-colors ${
                    active === s.id ? 'text-slate-900 font-semibold' : 'text-slate-400 hover:text-slate-700'
                  }`}
                >
                  {s.label}
                </button>
              ))}
            </nav>
          </aside>

          {/* Main Content */}
          <main className="flex-1 min-w-0">
            {/* Page Header */}
            <div className="mb-10 pb-8 border-b border-slate-100">
              <h1 className="text-3xl font-bold text-slate-900 mb-3">Privacy Policy</h1>
              <p className="text-sm text-slate-500">Effective date: August 11, 2026 · Governed by India's DPDP Act, 2023 and IT Act, 2000</p>
            </div>

            <div className="prose-legal">

              <section id="introduction" className="mb-10 scroll-mt-24">
                <h2>1. Introduction</h2>
                <p>JobPortal India ("we", "us", or "our") operates a job marketplace connecting Job Seekers, Employers, and Affiliate Agents across India. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal data.</p>
                <p>By accessing our platform, you agree to the terms of this policy. We act as a <strong>Data Fiduciary</strong> under the Digital Personal Data Protection Act, 2023 ("DPDP Act"). You are the <strong>Data Principal</strong>.</p>
              </section>

              <section id="information-we-collect" className="mb-10 scroll-mt-24">
                <h2>2. Information We Collect</h2>
                <p>We collect information you provide directly and data generated by your use of the platform.</p>
                <h3>Job Seekers</h3>
                <ul>
                  <li>Name, email address, and phone number</li>
                  <li>Resume, employment history, and educational background</li>
                  <li>Job preferences and skills</li>
                </ul>
                <h3>Employers</h3>
                <ul>
                  <li>Company name, GSTIN or PAN, and business address</li>
                  <li>Contact person name and email</li>
                  <li>Job listing details and billing information via Razorpay</li>
                </ul>
                <h3>Affiliate Agents</h3>
                <ul>
                  <li>Full name, date of birth, and phone number</li>
                  <li>KYC documents: Aadhar Card, PAN Card, Voter ID, or Passport number</li>
                  <li>Payout credentials: UPI ID or Bank Account Number, IFSC Code, and MICR Code (encrypted at rest)</li>
                </ul>
                <h3>Technical Data</h3>
                <ul>
                  <li>IP address, login timestamps, browser type, and device information</li>
                  <li>Cookies and session identifiers</li>
                </ul>
              </section>

              <section id="how-we-use" className="mb-10 scroll-mt-24">
                <h2>3. How We Use Your Data</h2>
                <p>We use your information only for the purposes for which it was collected:</p>
                <ul>
                  <li>To match Job Seekers with relevant job listings</li>
                  <li>To allow Employers to post and manage job listings</li>
                  <li>To process payments for job post credits via Razorpay</li>
                  <li>To verify Affiliate Agent identity (KYC) and disburse referral earnings via UPI or bank transfer</li>
                  <li>To detect fraud, enforce platform policies, and maintain security</li>
                  <li>To send transactional emails such as payment confirmations and account notices</li>
                </ul>
              </section>

              <section id="legal-basis" className="mb-10 scroll-mt-24">
                <h2>4. Legal Basis for Processing</h2>
                <p>Under Section 6 of the DPDP Act 2023, we process your personal data on the following grounds:</p>
                <ul>
                  <li><strong>Consent:</strong> You have provided clear, informed, and specific consent for the stated purposes.</li>
                  <li><strong>Contractual necessity:</strong> Processing is required to fulfil our service obligations, such as disbursing agent payouts.</li>
                  <li><strong>Legitimate use:</strong> For fraud prevention, platform security, and compliance with applicable Indian law.</li>
                </ul>
                <p>You may withdraw consent at any time by contacting us or deleting your account. Withdrawal does not affect the lawfulness of processing done before the withdrawal.</p>
              </section>

              <section id="sharing" className="mb-10 scroll-mt-24">
                <h2>5. Sharing & Disclosure</h2>
                <p>We do not sell your personal data. We share it only under the following limited circumstances:</p>
                <ul>
                  <li><strong>With Employers:</strong> When you apply for a job, your profile and resume are shared with the posting employer.</li>
                  <li><strong>With payment processors:</strong> Razorpay processes all card, UPI, and net banking transactions. We do not store card credentials.</li>
                  <li><strong>With cloud infrastructure providers:</strong> For hosting, storage, and database services.</li>
                  <li><strong>With law enforcement:</strong> When legally required under Section 69 of the IT Act, 2000 or any applicable court order.</li>
                </ul>
              </section>

              <section id="data-security" className="mb-10 scroll-mt-24">
                <h2>6. Data Security</h2>
                <p>We implement reasonable technical and organizational measures to protect your personal data from unauthorized access, alteration, or destruction:</p>
                <ul>
                  <li>All data in transit is protected using TLS/SSL encryption.</li>
                  <li>Sensitive payout credentials (bank accounts and UPI IDs) are encrypted at rest.</li>
                  <li>Copy-paste is disabled on payout input fields in the Agent console to prevent input errors.</li>
                  <li>Access to personal data is restricted to authorized personnel on a need-to-know basis.</li>
                </ul>
                <p>Despite these measures, no system is completely secure. You are responsible for keeping your login credentials confidential.</p>
              </section>

              <section id="your-rights" className="mb-10 scroll-mt-24">
                <h2>7. Your Rights</h2>
                <p>As a Data Principal under the DPDP Act 2023, you have the following rights:</p>
                <ul>
                  <li><strong>Right to access:</strong> Request a summary of personal data we hold about you.</li>
                  <li><strong>Right to correction:</strong> Request rectification of inaccurate or incomplete data.</li>
                  <li><strong>Right to erasure:</strong> Request deletion of your account and associated personal data.</li>
                  <li><strong>Right to withdraw consent:</strong> Stop processing at any time, subject to legal obligations.</li>
                  <li><strong>Right to nominate:</strong> Designate another person to exercise your rights in case of incapacity or death.</li>
                  <li><strong>Right to grievance redressal:</strong> File a complaint with our Grievance Officer or the Data Protection Board of India.</li>
                </ul>
                <p>To exercise any of these rights, email us at <a href="mailto:grievance.officer@jobportal.in">grievance.officer@jobportal.in</a>.</p>
              </section>

              <section id="retention" className="mb-10 scroll-mt-24">
                <h2>8. Data Retention</h2>
                <p>We retain your personal data for as long as your account is active or as necessary to provide services. Payment and transaction records are retained for a minimum of 7 years in compliance with the Income Tax Act, 1961, and the Companies Act, 2013. After the retention period, data is securely deleted or anonymized.</p>
              </section>

              <section id="cookies" className="mb-10 scroll-mt-24">
                <h2>9. Cookies</h2>
                <p>We use session cookies to maintain authentication state and analytics cookies to understand usage patterns. We do not use third-party advertising cookies. You may disable cookies in your browser settings; however, some platform features may not function correctly without them.</p>
              </section>

              <section id="changes" className="mb-10 scroll-mt-24">
                <h2>10. Changes to This Policy</h2>
                <p>We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email or by a prominent notice on the platform at least 15 days before the changes take effect. Your continued use of the platform after the effective date constitutes your acceptance of the revised policy.</p>
              </section>

              <section id="grievance" className="mb-10 scroll-mt-24">
                <h2>11. Grievance Officer</h2>
                <p>In compliance with Rule 3(11) of the IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and the DPDP Act, 2023, we have designated a Grievance Officer:</p>
                <div className="bg-slate-50 border border-slate-200 rounded-lg p-5 mt-4 space-y-1.5 text-sm">
                  <p><strong>Name:</strong> Mr. Rajesh Kumar</p>
                  <p><strong>Designation:</strong> Grievance Redressal Officer & Data Protection Officer</p>
                  <p><strong>Address:</strong> 4th Floor, Salarpuria GR Tech Park, Whitefield, Bengaluru, Karnataka – 560066</p>
                  <p><strong>Email:</strong> <a href="mailto:grievance.officer@jobportal.in">grievance.officer@jobportal.in</a></p>
                  <p><strong>Response time:</strong> We will acknowledge your complaint within 48 hours and resolve it within 15 business days.</p>
                </div>
              </section>

            </div>
          </main>

        </div>
      </div>

      <style>{`
        .prose-legal h2 {
          font-family: var(--font-heading);
          font-size: 18px;
          font-weight: 700;
          color: #111827;
          margin-top: 0;
          margin-bottom: 12px;
        }
        .prose-legal h3 {
          font-family: var(--font-heading);
          font-size: 14px;
          font-weight: 700;
          color: #374151;
          margin-top: 16px;
          margin-bottom: 6px;
        }
        .prose-legal p {
          font-size: 14px;
          color: #4B5563;
          line-height: 1.7;
          margin-bottom: 12px;
        }
        .prose-legal ul {
          padding-left: 20px;
          margin-bottom: 12px;
        }
        .prose-legal li {
          font-size: 14px;
          color: #4B5563;
          line-height: 1.7;
          margin-bottom: 4px;
        }
        .prose-legal a {
          color: #6366f1;
          text-decoration: underline;
        }
        .prose-legal a:hover {
          color: #4f46e5;
        }
        .prose-legal strong {
          color: #111827;
          font-weight: 600;
        }
      `}</style>
    </div>
  );
};

export default PrivacyPolicy;
